version: '3'

services:
  app:
    image: "dqc:${TAG}"
    container_name: dqc
    build: ./
    env_file:
      - .env
    volumes:
      - ${PWD}/dqc.log:/app/log/dqc.log
      - ${PWD}/settings.json:/app/settings.json
